 # This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: BuildAndDeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Pipeline-Learn/Pipeline-WebApp/Pipeline-WebApp.csproj
    - name: Build
      run: dotnet build  ./Pipeline-Learn/Pipeline-WebApp/Pipeline-WebApp.csproj

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Test
      run: dotnet test  --verbosity normal ./Pipeline-Learn/TestProject-PipeLine-Learn/TestProject-PipeLine-Learn.csproj

    