# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Provisioning

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Pipeline-Learn/Provisioning/**'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - uses: azure/login@v1
      with:
        careds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Pipeline-Learn/Provisioning/parameters.json

    - name: Logout via Azure CLI
      run: az logout